### ISSUE TITLE
Notebooks no longer work with V1.0 release

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/search-api-notebook#6] opened 2022-06-22 07:00 UTC
## 🐛 Describe the bug

* Data in the registry is incorrect
* Queries go against pds-gamma instead of ops registry

**Comment by jordanpadams** [comment] 2022-12-06 22:46
@tloubrieu-jpl do we actually plan on fixing this during this sprint, of should we add this to the top of the release backlog?

**Comment by jordanpadams** [comment] 2023-01-06 21:51
@jjacob7734 see PRs for some attempts at fixing this

**Comment by jordanpadams** [comment] 2023-01-06 21:52
note: this should work for the latest registry / API on main (and maybe tagged for release?). not necessarily what is online (which doesn't work)

**Comment by jordanpadams** [comment] 2023-01-06 21:53
feel free to ping @jimmie for some help here as well since he is digging into the tagged releases vs what is online vs what is going wrong

**Comment by jjacob7734** [comment] 2023-01-10 18:29
I got the `api_client.ipynb` to work with a couple modifications (not yet checked in).
1. Changed `configuration.host` from:

https://pds-gamma.jpl.nasa.gov/api/

to:

https://pds.nasa.gov/api/search-en-gamma/1.1/

**Reference**: Based on information from the Slack discussion between @eddiesarevalo and @jimmie here: https://jpl.slack.com/archives/GCGR1R3A4/p1673301753096449

2. Changed:

`api_response = api_instance.get_collection(...)`

to the following:

`from pds.api_client.api.collections_api import CollectionsApi`
`collections = CollectionsApi(api_client)`
`...`
`api_response = collections.get_collection(...)`

**Reference**: API documentation at https://github.com/NASA-PDS/pds-api-client/blob/main/docs/source/quickstart/index.rst

**Comment by jjacob7734** [comment] 2023-01-10 18:29
I got the `api_client.ipynb` to work with a couple modifications (not yet checked in).
1. Changed `configuration.host` from:

https://pds-gamma.jpl.nasa.gov/api/

to:

https://pds.nasa.gov/api/search-en-gamma/1.1/

**Reference**: Based on information from the Slack discussion between @eddiesarevalo and @jimmie here: https://jpl.slack.com/archives/GCGR1R3A4/p1673301753096449

2. Changed:

`api_response = api_instance.get_collection(...)`

to the following:

`from pds.api_client.api.collections_api import CollectionsApi`
`collections = CollectionsApi(api_client)`
`...`
`api_response = collections.get_collection(...)`

**Reference**: API documentation at https://github.com/NASA-PDS/pds-api-client/blob/main/docs/source/quickstart/index.rst

**Comment by jordanpadams** [comment] 2023-01-10 18:48
@jjacob7734 awesome! can you create a PR for this?

**Comment by jordanpadams** [comment] 2023-01-10 18:50
also @jjacob7734 even if we have PR, we may want to hold off until @jimmie deploys the latest registry to ops. the URL for the API should really be: https://pds.nasa.gov/api/search/1/

**Comment by jordanpadams** [comment] 2023-01-17 21:07
looking at OVIRS notebooks, which is not working right now.

**Comment by jordanpadams** [comment] 2023-01-17 21:07
looking at OVIRS notebooks, which is not working right now.

**Comment by jimmie** [comment] 2023-01-19 22:33
familiarizing w/ API, specifically the new python version that Thomas made available. Seeing an issue where a collection by lidvid is returning a 404 but works w/ curl and otherwise works w/out version.

**Comment by jjacob7734** [comment] 2023-01-20 00:28
It turns out the curl command was "working" because it was malformed.  The root of the problem is that the LIDVID I was trying to access does not exist in the production PDS registry.  It exists in a particular profile of the registry that can be deployed locally for test.  The new api_client does seem to be working fine if I give it a valid LIDVID.

**Comment by tloubrieu-jpl** [comment] 2023-01-26 22:07
What to do with the notebook needs to be refined.

**Comment by tloubrieu-jpl** [comment] 2023-01-31 21:37
Some part of the notebook is blocked by api issues.

We are not sure if the same data is still available in the registry.

**Comment by tloubrieu-jpl** [comment] 2023-02-09 22:19
The short term solution is to use only the /products end-point.

**Comment by jordanpadams** [comment] 2023-02-14 21:29
Status: working to change to just use the product API

**Comment by tloubrieu-jpl** [comment] 2023-02-28 22:03
Keep the following notebooks:
- part1/...
- part2/ standalone

We need a clear description of what they do for the users (in introduction of the notebook).

Remove part2/find_data

We move all the others in a `draft`. folder.

**Comment by jjacob7734** [comment] 2023-02-28 22:19
@jordanpadams @tloubrieu-jpl  recorded talk on PDS API:  https://www.youtube.com/watch?v=iuPzeZMbhrs

**Comment by tloubrieu-jpl** [comment] 2023-03-02 22:30
@jjacob7734 start to work on part1 notebook

**Comment by tloubrieu-jpl** [comment] 2023-03-09 22:30
The expected outcome is to fully review the notebooks that we want and ideintify the blocker on the server side.
Then a ticket will be created for react to each of the removed blockers.

**Comment by tloubrieu-jpl** [comment] 2023-03-14 20:32
@jjacob7734 is missing a way to apply the criteria, we will discuss that at the breakout.

**Comment by tloubrieu-jpl** [comment] 2023-03-21 20:19
@jjacob7734 is testing the pagination in he notebook. He is going to test the performances.

We also need to deploy the update in the opensearch configuration to go beyond the 10000 limit.

**Comment by tloubrieu-jpl** [comment] 2023-04-04 20:09
The updates are in branch TBC and will be tested on the new registry deployed in production.

The SBN-PDS node needs to reload their data as well.

**Closed** 2023-06-21 23:21 UTC
Labels: B13.1, bug, s.medium
